# render.yaml
databases:
  - name: tlapa-db
    databaseName: tlapa_db
    user: tlapa_user
    plan: free

services:
  - type: web
    name: tlapa-multiservicios
    env: node
    plan: free
    buildCommand: "npm install && npx prisma generate && npx prisma migrate deploy && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tlapa-db
          property: connectionString
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false # Configurar en el dashboard de Render
